name: Update Main Branch

on:
  push:
    branches:
      - prod

jobs:
  update_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge prod into main
        run: |
          git config --global user.email "{{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "{{ secrets.GIT_USER_NAME }}"
          git checkout main
          git merge --no-ff prod -m "Merge prod into main"
          git push origin main
