name: Update Main Branch

on:
  push:
    branches:
      - prod

jobs:
  update_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set Git user email
        run: git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
    
      - name: Set Git user name
        run: git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Print all branches
        run: |
          git fetch --all --quiet
          git branch -r | grep -v '\->' | while read branch; do echo "${branch#origin/}"; done
          
      - name: Merge prod into main
        run: |
          git checkout main
          git merge --no-ff prod -m "Merge prod into main" --allow-unrelated-histories
          git push origin main
